# Generated by Django 4.1.5 on 2023-01-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalintroductionformanswer',
            name='metier',
            field=models.CharField(choices=[('Chef de cuisine et pâtissier propriétaire', 'Chef Proprietaire'), ('Chef de cuisine et pâtissier salarié actionnaire', 'Chef Salarie Actionnaire'), ('Chef de cuisine et pâtissier salarié ', 'Chef Salarie')], max_length=90),
        ),
    ]
