# Generated by Django 4.1.5 on 2023-01-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntroductionFormAnswers',
            new_name='IntroductionFormAnswer',
        ),
    ]
