# Generated by Django 4.1.5 on 2023-02-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0004_alter_sharingalert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharingalert',
            name='user',
        ),
        migrations.AddField(
            model_name='sharingalert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
