# Generated by Django 4.1.5 on 2023-02-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0005_remove_sharingalert_user_sharingalert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='restaurant_city',
        ),
    ]
