# Generated by Django 4.1.5 on 2023-02-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0006_remove_player_restaurant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteformanswer',
            name='frequence_modification',
            field=models.CharField(choices=[('Tous les jours', 'tous les jours'), ('Toutes les semaines', 'toutes les semaines'), ('Tous les mois', 'tous les mois'), ('Par saison', 'par saison'), ('Autre', 'autre')], max_length=90),
        ),
        migrations.AlterField(
            model_name='carteformanswer',
            name='frequence_suggestion_du_jour',
            field=models.CharField(choices=[("Je n'en fais pas", "je n'en fais pas"), ('Tous les jours', 'je les change tous les jours'), ('Tous les deux jours', 'je les change tous les deux jours'), ('Toutes les semaines', 'je les change toutes les semaines'), ('Autre', 'autre')], max_length=90),
        ),
        migrations.AlterField(
            model_name='carteformanswer',
            name='prix_trouve_justes_clients',
            field=models.CharField(choices=[('Oui, suffisament juste', 'oui, suffisament justes'), ('Non', 'non'), ('Pas sûr', 'pas sûr')], max_length=90),
        ),
        migrations.AlterField(
            model_name='carteformanswer',
            name='prix_trouve_justes_soi',
            field=models.CharField(choices=[('Oui, suffisament juste', 'oui, suffisament justes'), ('Non', 'non'), ('Pas sûr', 'pas sûr')], max_length=90),
        ),
        migrations.AlterField(
            model_name='carteformanswer',
            name='rythme_trouve_suffisant',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='commandeformanswer',
            name='methode_classement_factures',
            field=models.CharField(choices=[('classeur', 'Classeur'), ('trieur', 'Trieur'), ('ordinateur', 'Ordinateur'), ('comptabilite', 'envoi\xa0à la comptabilité en direct'), ('Autre', 'Autre')], max_length=90),
        ),
        migrations.AlterField(
            model_name='comptaformanswer',
            name='souhait_plus_de_regularite',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='connaissanceachatformanswer',
            name='analyse_ligne_a_ligne_possible',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='connaissanceachatformanswer',
            name='connaissance_quantite_par_fournisseur',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='connaissanceachatformanswer',
            name='connaissance_repartition_par_categorie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='generalintroductionformanswer',
            name='metier',
            field=models.CharField(choices=[('Chef de cuisine et pâtissier propriétaire', 'chef de cuisine et pâtissier propriétaire'), ('Chef de cuisine et pâtissier salarié actionnaire', 'chef de cuisine et pâtissier salarié actionnaire'), ('Chef de cuisine et pâtissier salarié', 'chef de cuisine et pâtissier salarié')], max_length=90),
        ),
        migrations.AlterField(
            model_name='recetteformanswer',
            name='est_ce_trop',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='recetteformanswer',
            name='methode_transmission_savoir',
            field=models.CharField(choices=[('Oralement', 'oralement'), ('Sur papier volant', 'sur papier volant'), ('Dans un classeur', "à l'aide de classeurs"), ('Autre', 'autre')], max_length=90),
        ),
        migrations.AlterField(
            model_name='recetteformanswer',
            name='satisfait_mode_transmission',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='recetteformanswer',
            name='satisfait_support_memorisation',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=90),
        ),
        migrations.AlterField(
            model_name='recetteformanswer',
            name='support_memorisation',
            field=models.CharField(choices=[('sur du papier volant', 'sur du papier volant'), ('Sur un carnet', 'sur un carnet'), ('Excel ou autre tableur', 'sur Excel ou un autre tableur'), ('Word ou autre éditeur', 'sur Word ou autre éditeur'), ('Autre outil informatique', 'grâce à un autre outil informatique'), ('Autre', 'autre')], max_length=90),
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_title', models.CharField(max_length=150)),
                ('answer', models.TextField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form_and_game.player')),
            ],
        ),
    ]
