# Generated by Django 4.1.5 on 2023-02-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0007_alter_carteformanswer_frequence_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='needs_precising',
            field=models.BooleanField(default=True),
        ),
    ]
