# Generated by Django 4.1.5 on 2023-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0008_player_needs_precising'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='was_added_precision_points',
            field=models.BooleanField(default=False),
        ),
    ]
