# Generated by Django 4.1.5 on 2023-02-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0009_player_was_added_precision_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='booked_phone_call',
            field=models.BooleanField(default=False),
        ),
    ]
