# Generated by Django 4.1.5 on 2023-02-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_and_game', '0011_alter_commandeformanswer_methode_classement_bons_livraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='randomly_created',
            field=models.BooleanField(default=False),
        ),
    ]
